spring.application.name=SmartLogix
spring.profiles.active=local

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=true
spring.flyway.out-of-order=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false 
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.com.cognizant.smartlogix=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

